#pragma kernel Vote
#pragma kernel Scan
#pragma kernel ScanGroupSums
#pragma kernel Compact
// #pragma kernel ResetArgs

struct GrassData 
{
    float4 position;
    float3 up;
    float3 forward;
    float2 scale;
};

RWStructuredBuffer<GrassData> _GrassDataBuffer;
RWStructuredBuffer<uint> _VoteBuffer;
RWStructuredBuffer<uint> _ScanBuffer;
RWStructuredBuffer<uint> _ScanGroupSumArray;
RWStructuredBuffer<uint> _ScanGroupSumArrayIn;
RWStructuredBuffer<uint> _ScanGroupSumArrayOut;
RWStructuredBuffer<GrassData> _CulledGrassOutputBuffer;
RWStructuredBuffer<uint> _ArgsBuffer;

float4x4 MATRIX_VP; //view projection matrix
float3 _CameraPosition;
float _MaxDrawDistance;

groupshared uint temp[2 * 64]; 
groupshared uint grouptemp[2 * 1024]; 
int _ScanNumOfGroups;

Texture2D<float4> _DetailMap;
SamplerState _DetailMapPointClampSampler;
float3 _DetailSplatMapChannels;

[numthreads(128, 1, 1)]
void Vote(uint3 id : SV_DispatchThreadID)
{
    float4 position = float4(_GrassDataBuffer[id.x].position.xyz, 1.0f);
    
    //transform point into clipspace by mul view projection matrix
    float4 clipspace = mul(MATRIX_VP, position); 

    //clipspace into NDC (normalized device coordinates)
    ///THIS IS NOT SCREEN SPACE, SCREEN SPACE IS NDC CONVERTED INTO PIXEL COORDINATES EG 0 TO 1920
    //normalizes clipspace from -w to w into 0 to 1, NDC.x 0 being left 1 being right, NDC.y 0 being bottom 1 being top
    float3 NDC = clipspace.xyz; 
    NDC /= -clipspace.w; //-1 to 1

    //change into 0 to 1
    NDC.x = NDC.x / 2.0f + 0.5f;
    NDC.y = NDC.y / 2.0f + 0.5f;
    NDC.z = clipspace.w; //if w is position point is in front of camera if negative or near zero its behind or at camera

    bool inView = NDC.x < -0.2f || NDC.x > 1.2f || NDC.z <= -0.1f ? 0 : 1;
    //bool withinDistance = distance(_CameraPosition, position.xyz) < _MaxDrawDistance;

    _VoteBuffer[id.x] = inView;
}

//Each group will have 64 threads and each thread handles 2 vote elements
//The group cooperatively performs a Blelloch parallel prefix scan
//across all 128 elements (64 threads x 2 elements), via up-sweep/down-sweep
[numthreads(64, 1, 1)]
//id is your thread id among all groups
//group index is your index within your group per dimension
//group id is your groups index
//group thread id tells you which index within your group and which dimension u in, example index 5 in x dimension will be (5, 0, 0)
void Scan(uint3 id : SV_DISPATCHTHREADID, uint groupIndex : SV_GROUPINDEX, uint3 _groupID : SV_GROUPID, uint3 groupThreadID : SV_GROUPTHREADID)
{
    uint tid = id.x; //thread id
    uint groupTID = groupThreadID.x; //group thread id
    uint groupID = _groupID.x; //group id
    
    int offset = 1; //or stide
    
    //start, the thread copy 2 elements from vote buffer into temp
    //lets say for thread 0 within a group
    //groupTID will be 0
    //tid will be 0
    //so its very start of scan
    
    //first element will be temp[0] = _VoteBuffer[2 * 0]  //why 2*tid cause we process 2 elements so we skip ahead 2, look 2nd element below
    //temp[0] = _VoteBuffer[0] 
    
    //2nd element will be temp[2 * 0 + 1] = _VoteBuffer[2 * 0 + 1];  // see we + 1 
    //temp[1] = _VoteBuffer[1];
    
    //now we effectively copied the first 2 elements from vote buffer to temp
    temp[2 * groupTID] = _VoteBuffer[2 * tid]; //first elemnent
    temp[2 * groupTID + 1] = _VoteBuffer[2 * tid + 1]; //2nd element
    int d;
    int numElements = 2 * 64; 
    
    //gpu processes bitwise operations faster 
    //d >> 1 is bitshift by 1 is essentially dividing 2 so d/2
    //d >>= 1 shift by 1 and store it back into d so d/=2
    
    //Upsweep reduction loop, build sum and place up the tree
    for (d = numElements >> 1; d > 0; d >>= 1)
    {
        GroupMemoryBarrierWithGroupSync(); //waits for all threads within group to finish before continuing
        //each thread only starts next layer when rest complete
        
        //if d = 64 and groupTID = 0 loop 7 times
        //then result of upsweep will be the total elements at root index so temp[127] = 2 
        if (groupTID < d) {
            int ai = offset * (2 * groupTID + 1) - 1;
            int bi = offset * (2 * groupTID + 2) - 1;
            temp[bi] += temp[ai];
        }

        offset *= 2;
    }
    
    if (groupTID == 0) 
    {
        //store upsweep result into group sum array with index of GROUP ID NOT GROUP THREAD ID
        //numElements - 1 is your root node
        _ScanGroupSumArray[_groupID.x] = temp[numElements - 1]; //sum of all elements in group //sum of all valid votes the group is handling
        temp[numElements - 1] = 0; //set to 0 then begin down sweep
    }
    
    //Downsweep
    //start from 1 then double per loop opposite of upsweep
    for (d = 1; d < numElements; d *= 2) 
    {
        offset >>= 1;

        GroupMemoryBarrierWithGroupSync();
        
        if (groupTID < d) {
            int ai = offset * (2 * groupTID + 1) - 1;
            int bi = offset * (2 * groupTID + 2) - 1;
            int t = temp[ai]; 
            temp[ai] = temp[bi]; //swap
            temp[bi] += t; //add
        }
    }
 
    //results of scan gives us the ordered segment of the vote array this is not the full ordered vote array
    GroupMemoryBarrierWithGroupSync();

    _ScanBuffer[2 * tid] = temp[2 * groupTID];
    _ScanBuffer[2 * tid + 1] = temp[2 * groupTID + 1];
}

//Group Scan takes each groups total and properly tells you how many total comes before it
//Example group 0 sum is 40
//group 1 sum is 38
//_GroupSumArray[0] = 40
//_GroupSumArray[1] = 38 //but we want it to be 40 + 38
[numthreads(1024, 1, 1)] //Use one large thread group so the group sum scan can process the padded group sum array in a single group
//1024 threads * 2 elements = 2048 group sums max, covering up to 262,144 grass instances (2048 * 128)
//Big enough too keep this as one thread group so all group sums can be scanned together in shared memory, avoiding another hierarchical scan level
//More than 2024 groups sums or 262,144 grass instances will just not be processed more require another hierarchical scan level
//1024 is max amount of threads in 1 group in directX u cannot increase more
void ScanGroupSums(uint3 id : SV_DISPATCHTHREADID, uint groupIndex : SV_GROUPINDEX, uint3 _groupID : SV_GROUPID, uint3 groupThreadID : SV_GROUPTHREADID)
{
    uint tid = id.x;
    uint groupTID = groupThreadID.x;
    uint groupID = _groupID.x;

    int offset = 1;
    grouptemp[2 * groupTID] = _ScanGroupSumArrayIn[2 * tid];
    grouptemp[2 * groupTID + 1] = _ScanGroupSumArrayIn[2 * tid + 1];
    int d;

    //Upsweep
    for (d = _ScanNumOfGroups >> 1; d > 0; d >>= 1) 
    {
        GroupMemoryBarrierWithGroupSync();

        if (groupTID < d) {
            int ai = offset * (2 * groupTID + 1) - 1;
            int bi = offset * (2 * groupTID + 2) - 1;
            grouptemp[bi] += grouptemp[ai];
        }

        offset *= 2;
    }

    //Set root node to 0
    if (tid == 0)
        grouptemp[_ScanNumOfGroups - 1] = 0;

    //Downsweep
    for (d = 1; d < _ScanNumOfGroups; d *= 2) 
    {
        offset >>= 1;

        GroupMemoryBarrierWithGroupSync();
        if (tid < d) {
            int ai = offset * (2 * groupTID + 1) - 1;
            int bi = offset * (2 * groupTID + 2) - 1;
            int t = grouptemp[ai];
            grouptemp[ai] = grouptemp[bi];
            grouptemp[bi] += t;
        }
    }

    GroupMemoryBarrierWithGroupSync();

    _ScanGroupSumArrayOut[2 * tid] = grouptemp[2 * tid];
    _ScanGroupSumArrayOut[2 * tid + 1] = grouptemp[2 * tid + 1];
    //Now we have arranged group sum total where each index sum is the accumulation of all the prev index sum
}

//Using the group sum array and the scan array we now can organize the culled valid grass positions
[numthreads(128, 1, 1)]
void Compact(uint3 id : SV_DISPATCHTHREADID, uint groupIndex : SV_GROUPINDEX, uint3 _groupID : SV_GROUPID, uint3 groupThreadID : SV_GROUPTHREADID)
{
    uint tid = id.x; 
    uint groupID = _groupID.x;
    uint groupSum = groupID > 0 ? _ScanGroupSumArray[groupID] : 0;
    
    if (_VoteBuffer[tid] == 1) //if valid
    {
        InterlockedAdd(_ArgsBuffer[1], 1); //adds 1 to count of args[1] which is the number of instances
        _CulledGrassOutputBuffer[_ScanBuffer[tid] + groupSum] = _GrassDataBuffer[tid];
    }
}

// //Reset the indirect draw instance count before culling and counting visible grass
// [numthreads(1, 1, 1)]
// void ResetArgs(uint3 id : SV_DISPATCHTHREADID) 
// {
//     _ArgsBuffer[1] = (uint)0;
// }