#pragma kernel InitializeGrass

#include "Assets/Art/Shaders/SimplexNoise3D.hlsl"
#include "UnityCG.cginc"
#include "Assets/Art/Shaders/Random.cginc"
#define kMaxHeight (32766.0f/65535.0f) //needed for height map check TerrainTools docs

struct GrassData 
{
    float4 position;
    float3 up;
    float yawAngle;
    float2 scale;
};

uint _Resolution;
RWStructuredBuffer<GrassData> _GrassDataBuffer;

float3 _TerrainPosition;
float3 _TerrainSize;
float2 _Scale;

Texture2D<float4> _HeightMap;
SamplerState _HeightMapPointClampSampler;

Texture2D<float4> _NormalMap;
SamplerState _NormalMapPointClampSampler;

[numthreads(8,8,1)]
void InitializeGrass(uint3 id : SV_DispatchThreadID) 
{
    //this gets index
    //check if less than resolution to prevent out of bounds
    if (id.x >= _Resolution || id.y >= _Resolution) return;
    uint index = id.x + id.y * _Resolution;
    
    GrassData grass = (GrassData)0;
    
    float2 uv = float2(id.xy) / (float(_Resolution) - 1); //uv space
    
    float jitterX = randValue(index) - 0.5f;
    float jitterY = randValue(index + 1) - 0.5f;
    float2 jitter = float2(jitterX, jitterY);
    uv += jitter / _Resolution;
    
    float3 position = _TerrainPosition;
    position.xz += uv * _TerrainSize.xz;
    
    float4 heightMapValue = _HeightMap.SampleLevel(_HeightMapPointClampSampler, uv, 0);
    float unpackHeight = UnpackHeightmap(heightMapValue); //needed check TerrainTools docs
    float height = unpackHeight * (_TerrainSize.y / kMaxHeight);
    position.y += height;
    
    grass.position = float4(position, 1.0);
    
    grass.yawAngle = randValue(index) * 180.0;
    
    grass.scale = 1.0 + (randValue(index) - 0.5) * _Scale;
    
    float4 normalMapValue = _NormalMap.SampleLevel(_NormalMapPointClampSampler, uv, 0);
    grass.up.xyz = normalMapValue.xyz;

    _GrassDataBuffer[index] = grass;
    
}
